version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: api-gateway-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2

  service1:
    build:
      context: ./service1
    ports:
      - "8001:8000"
    working_dir: /app
    volumes:
      - ./service1/:/app

  service2:
    build:
      context: ./service2
    ports:
      - "8002:8000"
    working_dir: /app
    volumes:
      - ./service2/:/app

  # Agrega más servicios si es necesario
